In [1]:
import pandas as pd
import numpy as np
import matplotlib
matplotlib.use("Agg")
import matplotlib.pyplot as plt
import seaborn as sns

pd.set_option("display.max_columns", None)
pd.set_option("display.max_rows", 100)
pd.set_option("display.max_colwidth", 100)

sns.set_theme(style="whitegrid")

In [2]:
df = pd.read_csv("../data/patient_clinical_data_raw.csv")

df.head()

,Patient_ID,Age,Gender,Department,Blood_Pressure,Heart_Rate,Temperature,Cholesterol,Glucose,Diagnosis,Admission_Type,Length_of_Stay,Treatment_Cost,Readmission
0,P07402,58.0,Female,Orthopedics,119/73,64.0,100.0,197.0,60.0,Heart Disease,Referral,5,91183.33,No
1,P05835,NaN,Female,General Medicine,107/91,62.0,98.8,215.0,92.0,Migraine,Referral,5,71104.32,No
2,P02123,47.0,Male,Orthopedics,148/98,83.0,96.0,196.0,133.0,Fracture,Routine,7,135197.73,No
3,P08789,NaN,Male,Oncology,115/84,89.0,100.1,224.0,119.0,Hypertension,Referral,6,146462.06,No
4,P00305,47.0,Female,Orthopedics,128/62,77.0,100.3,184.0,113.0,Hypertension,Emergency,6,57510.66,No

In [3]:
rows, columns = df.shape

print(f"Number of rows    : {rows}")
print(f"Number of columns : {columns}")

Number of rows    : 10100
Number of columns : 14

In [4]:
df.columns.tolist()

['Patient_ID',
 'Age',
 'Gender',
 'Department',
 'Blood_Pressure',
 'Heart_Rate',
 'Temperature',
 'Cholesterol',
 'Glucose',
 'Diagnosis',
 'Admission_Type',
 'Length_of_Stay',
 'Treatment_Cost',
 'Readmission']

In [5]:
df.dtypes

Patient_ID            str
Age               float64
Gender                str
Department            str
Blood_Pressure        str
Heart_Rate        float64
Temperature       float64
Cholesterol       float64
Glucose           float64
Diagnosis             str
Admission_Type        str
Length_of_Stay      int64
Treatment_Cost    float64
Readmission           str
dtype: object

In [6]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 10100 entries, 0 to 10099
Data columns (total 14 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Patient_ID      10100 non-null  str
 1   Age             9798 non-null   float64
 2   Gender          10100 non-null  str
 3   Department      10100 non-null  str
 4   Blood_Pressure  10100 non-null  str
 5   Heart_Rate      9798 non-null   float64
 6   Temperature     9796 non-null   float64
 7   Cholesterol     9797 non-null   float64
 8   Glucose         9798 non-null   float64
 9   Diagnosis       10100 non-null  str
 10  Admission_Type  10100 non-null  str
 11  Length_of_Stay  10100 non-null  int64
 12  Treatment_Cost  10100 non-null  float64
 13  Readmission     10100 non-null  str
dtypes: float64(6), int64(1), str(7)
memory usage: 1.1 MB

In [7]:
df.describe(include="all")

,Patient_ID,Age,Gender,Department,Blood_Pressure,Heart_Rate,Temperature,Cholesterol,Glucose,Diagnosis,Admission_Type,Length_of_Stay,Treatment_Cost,Readmission
count,10100,9798.000000,10100,10100,10100,9798.000000,9796.000000,9797.000000,9798.000000,10100,10100,10100.000000,10100.000000,10100
unique,10000,NaN,5,9,3645,NaN,NaN,NaN,NaN,8,3,NaN,NaN,2
top,P00108,NaN,Male,Oncology,125/78,NaN,NaN,NaN,NaN,Asthma,Routine,NaN,NaN,No
freq,2,NaN,4969,1681,13,NaN,NaN,NaN,NaN,1292,4455,NaN,NaN,8227
mean,NaN,47.418249,NaN,NaN,NaN,77.927740,98.399490,195.187098,106.199939,NaN,NaN,5.033960,100538.421836,NaN
std,NaN,18.021377,NaN,NaN,NaN,11.914117,1.199324,34.777238,28.656813,NaN,NaN,1.996912,42516.545663,NaN
min,NaN,-5.000000,NaN,NaN,NaN,45.000000,95.000000,100.000000,60.000000,NaN,NaN,1.000000,13492.020000,NaN
25%,NaN,35.000000,NaN,NaN,NaN,70.000000,97.600000,172.000000,85.000000,NaN,NaN,4.000000,68704.152500,NaN
50%,NaN,47.000000,NaN,NaN,NaN,78.000000,98.400000,195.000000,105.000000,NaN,NaN,5.000000,94104.265000,NaN
75%,NaN,60.000000,NaN,NaN,NaN,86.000000,99.200000,219.000000,126.000000,NaN,NaN,6.000000,125074.220000,NaN
max,NaN,150.000000,NaN,NaN,NaN,122.000000,102.900000,326.000000,209.000000,NaN,NaN,14.000000,315212.620000,NaN

In [8]:
unique_counts = df.nunique()

unique_counts

Patient_ID        10000
Age                  92
Gender                5
Department            9
Blood_Pressure     3645
Heart_Rate           75
Temperature          76
Cholesterol         206
Glucose             145
Diagnosis             8
Admission_Type        3
Length_of_Stay       14
Treatment_Cost     9998
Readmission           2
dtype: int64

In [9]:
categorical_columns = df.select_dtypes(include="object").columns

for column in categorical_columns:
    print(f"\n{'=' * 60}")
    print(f"{column}")
    print(f"{'=' * 60}")
    print(df[column].value_counts(dropna=False))

============================================================
Patient_ID
============================================================
Patient_ID
P00108    2
P00800    2
P05548    2
P01057    2
P00577    2
         ..
P05735    1
P05192    1
P05391    1
P00861    1
P07271    1
Name: count, Length: 10000, dtype: int64

============================================================
Gender
============================================================
Gender
Male        4969
Female      4829
male         101
 FEMALE      101
MALE         100
Name: count, dtype: int64

============================================================
Department
============================================================
Department
Oncology            1681
Orthopedics         1657
Pediatrics          1629
Neurology           1625
General Medicine    1624
Cardiology          1582
neurology            102
 CARDIOLOGY          100
cardiology           100
Name: count, dtype: int64

============================================================
Blood_Pressure
============================================================
Blood_Pressure
125/78     13
121/85     13
119/73     12
130/72     12
131/73     12
           ..
110/58      1
130/63      1
102/99      1
85/57       1
155/104     1
Name: count, Length: 3645, dtype: int64

============================================================
Diagnosis
============================================================
Diagnosis
Asthma           1292
Infection        1292
Cancer           1289
Diabetes         1286
Hypertension     1260
Migraine         1253
Fracture         1219
Heart Disease    1209
Name: count, dtype: int64

============================================================
Admission_Type
============================================================
Admission_Type
Routine      4455
Emergency    3566
Referral     2079
Name: count, dtype: int64

============================================================
Readmission
============================================================
Readmission
No     8227
Yes    1873
Name: count, dtype: int64

C:\Users\upadh\AppData\Local\Temp\ipykernel_9488\699186831.py:1: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  categorical_columns = df.select_dtypes(include="object").columns

## Part B : Data Cleaning

The dataset is checked for missing values, duplicate records, invalid ages,
and inconsistent categorical values. Appropriate cleaning techniques are
then applied while preserving the original clinical information wherever
possible.

In [10]:
missing_summary = pd.DataFrame({
    "Missing_Count": df.isnull().sum(),
    "Missing_Percentage": df.isnull().mean() * 100
})

missing_summary = (
    missing_summary[missing_summary["Missing_Count"] > 0]
    .sort_values("Missing_Percentage", ascending=False)
)

missing_summary

             Missing_Count  Missing_Percentage
Temperature            304            3.009901
Cholesterol            303            3.000000
Age                    302            2.990099
Heart_Rate             302            2.990099
Glucose                302            2.990099

In [11]:
numeric_columns = df.select_dtypes(include=np.number).columns

numeric_columns

Index(['Age', 'Heart_Rate', 'Temperature', 'Cholesterol', 'Glucose',
       'Length_of_Stay', 'Treatment_Cost'],
      dtype='str')

In [12]:
missing_before = df[numeric_columns].isnull().sum()

missing_before

Age               302
Heart_Rate        302
Temperature       304
Cholesterol       303
Glucose           302
Length_of_Stay      0
Treatment_Cost      0
dtype: int64

In [13]:
for column in numeric_columns:
    df[column] = df[column].fillna(df[column].median())

In [14]:
df[numeric_columns].isnull().sum()

Age               0
Heart_Rate        0
Temperature       0
Cholesterol       0
Glucose           0
Length_of_Stay    0
Treatment_Cost    0
dtype: int64

In [15]:
duplicate_count = df.duplicated().sum()

print(f"Number of duplicate records: {duplicate_count}")

Number of duplicate records: 100

In [16]:
df = df.drop_duplicates().reset_index(drop=True)

print(f"Rows after removing duplicates: {len(df)}")

Rows after removing duplicates: 10000

In [17]:
df["Age"].describe()

count    10000.000000
mean        47.390900
std         17.758374
min         -5.000000
25%         36.000000
50%         47.000000
75%         59.000000
max        150.000000
Name: Age, dtype: float64

In [18]:
invalid_age = df[
    (df["Age"] < 0) | (df["Age"] > 120)
]

invalid_age[["Patient_ID", "Age"]]

     Patient_ID    Age
39       P00304  150.0
399      P07151  150.0
682      P00684   -5.0
1214     P06801   -5.0
1413     P08175   -5.0
1612     P00555  150.0
2090     P01771   -5.0
2454     P02920   -5.0
3774     P09773   -5.0
4311     P02156   -5.0
5834     P08060   -5.0
6147     P06021   -5.0
6691     P00116  150.0
8487     P03639   -5.0
8981     P05183  150.0

In [19]:
invalid_age = df[
    (df["Age"] < 0) | (df["Age"] > 120)
]

invalid_age[["Patient_ID", "Age"]]

     Patient_ID    Age
39       P00304  150.0
399      P07151  150.0
682      P00684   -5.0
1214     P06801   -5.0
1413     P08175   -5.0
1612     P00555  150.0
2090     P01771   -5.0
2454     P02920   -5.0
3774     P09773   -5.0
4311     P02156   -5.0
5834     P08060   -5.0
6147     P06021   -5.0
6691     P00116  150.0
8487     P03639   -5.0
8981     P05183  150.0

In [20]:
age_median = df["Age"].median()

df["Age"] = df["Age"].fillna(age_median)

print(f"Median age used for invalid/missing values: {age_median:.2f}")

Median age used for invalid/missing values: 47.00

In [21]:
df["Age"].describe()

count    10000.000000
mean        47.390900
std         17.758374
min         -5.000000
25%         36.000000
50%         47.000000
75%         59.000000
max        150.000000
Name: Age, dtype: float64

In [22]:
df["Gender"].value_counts(dropna=False)

Gender
Male        4920
Female      4780
MALE         100
male         100
 FEMALE      100
Name: count, dtype: int64

In [23]:
df["Gender"] = (
    df["Gender"]
    .str.strip()
    .str.lower()
    .replace({
        "m": "Male",
        "male": "Male",
        "f": "Female",
        "female": "Female"
    })
)

In [24]:
df["Gender"].value_counts()

Gender
Male      5120
Female    4880
Name: count, dtype: int64

In [25]:
df["Department"].value_counts()

Department
Oncology            1662
Orthopedics         1644
Pediatrics          1614
Neurology           1612
General Medicine    1607
Cardiology          1561
 CARDIOLOGY          100
cardiology           100
neurology            100
Name: count, dtype: int64

In [26]:
df["Department"] = (
    df["Department"]
    .str.strip()
    .str.title()
)

In [27]:
df["Department"].value_counts()

Department
Cardiology          1761
Neurology           1712
Oncology            1662
Orthopedics         1644
Pediatrics          1614
General Medicine    1607
Name: count, dtype: int64

## Part C :  Data Transformation

New analytical features are created from the cleaned dataset to support
patient segmentation, clinical risk identification, and treatment-cost
analysis.

In [28]:
df["Age_Group"] = pd.cut(
    df["Age"],
    bins=[-np.inf, 17, 40, 60, np.inf],
    labels=[
        "Child",
        "Young Adult",
        "Middle Age",
        "Senior"
    ]
)

In [29]:
df["Age_Group"].value_counts()

Age_Group
Middle Age     4362
Young Adult    2901
Senior         2248
Child           489
Name: count, dtype: int64

In [30]:
df[["Systolic", "Diastolic"]] = (
    df["Blood_Pressure"]
    .str.split("/", expand=True)
)

In [31]:
df["Systolic"] = pd.to_numeric(
    df["Systolic"],
    errors="coerce"
)

df["Diastolic"] = pd.to_numeric(
    df["Diastolic"],
    errors="coerce"
)

In [32]:
df[
    [
        "Blood_Pressure",
        "Systolic",
        "Diastolic"
    ]
].head(10)

  Blood_Pressure  Systolic  Diastolic
0         119/73       119         73
1         107/91       107         91
2         148/98       148         98
3         115/84       115         84
4         128/62       128         62
5         104/85       104         85
6         118/83       118         83
7         122/89       122         89
8        161/100       161        100
9         102/76       102         76

In [33]:
df["High_Risk"] = (
    (df["Glucose"] > 140)
    | (df["Cholesterol"] > 240)
    | (df["Heart_Rate"] > 100)
    | (df["Systolic"] >= 140)
    | (df["Diastolic"] >= 90)
)

In [34]:
df["High_Risk"].value_counts()

High_Risk
True     5226
False    4774
Name: count, dtype: int64

In [35]:
df["Cost_Per_Day"] = (
    df["Treatment_Cost"] / df["Length_of_Stay"]
)

In [36]:
df[
    [
        "Patient_ID",
        "Treatment_Cost",
        "Length_of_Stay",
        "Cost_Per_Day"
    ]
].head(10)

  Patient_ID  Treatment_Cost  Length_of_Stay  Cost_Per_Day
0     P07402        91183.33               5  18236.666000
1     P05835        71104.32               5  14220.864000
2     P02123       135197.73               7  19313.961429
3     P08789       146462.06               6  24410.343333
4     P00305        57510.66               6   9585.110000
5     P02532       128417.99               5  25683.598000
6     P02996       106428.84               7  15204.120000
7     P07660       126644.27               5  25328.854000
8     P08225        76285.34               7  10897.905714
9     P04449       150822.91               6  25137.151667

## Part D Analysis

In [37]:
average_age = df["Age"].mean()

print(f"Average patient age: {average_age:.2f} years")

Average patient age: 47.39 years

In [38]:
patients_by_department = (
    df["Department"]
    .value_counts()
)

patients_by_department

Department
Cardiology          1761
Neurology           1712
Oncology            1662
Orthopedics         1644
Pediatrics          1614
General Medicine    1607
Name: count, dtype: int64

In [39]:
plt.figure(figsize=(10, 5))

sns.countplot(
    data=df,
    x="Department",
    order=df["Department"].value_counts().index
)

plt.title("Number of Patients by Department")
plt.xlabel("Department")
plt.ylabel("Number of Patients")
plt.xticks(rotation=45)
plt.tight_layout()
plt.savefig("../output/patient_count_by_department.png", dpi=150)
plt.show()

C:\Users\upadh\AppData\Local\Temp\ipykernel_9488\4106895982.py:15: UserWarning: FigureCanvasAgg is non-interactive, and thus cannot be shown
  plt.show()

In [40]:
average_cost_by_department = (
    df.groupby("Department")["Treatment_Cost"]
    .mean()
    .sort_values(ascending=False)
)

average_cost_by_department

Department
Cardiology          102040.799086
Neurology           101224.787389
General Medicine    100711.121568
Orthopedics         100302.539605
Oncology            100039.380927
Pediatrics           99036.600929
Name: Treatment_Cost, dtype: float64

In [41]:
average_stay_by_diagnosis = (
    df.groupby("Diagnosis")["Length_of_Stay"]
    .mean()
    .sort_values(ascending=False)
)

average_stay_by_diagnosis

Diagnosis
Hypertension     5.100881
Diabetes         5.080000
Migraine         5.045857
Fracture         5.030629
Infection        5.023585
Heart Disease    5.003333
Cancer           4.995309
Asthma           4.993721
Name: Length_of_Stay, dtype: float64

In [42]:
top_10_cost = (
    df.nlargest(10, "Treatment_Cost")
    [
        [
            "Patient_ID",
            "Age",
            "Gender",
            "Department",
            "Diagnosis",
            "Length_of_Stay",
            "Treatment_Cost"
        ]
    ]
)

top_10_cost

,Patient_ID,Age,Gender,Department,Diagnosis,Length_of_Stay,Treatment_Cost
1785,P09106,41.0,Male,Neurology,Infection,12,315212.62
9966,P01900,42.0,Female,Orthopedics,Infection,11,288519.47
4796,P06995,36.0,Male,Oncology,Asthma,12,286702.48
7306,P09616,55.0,Male,Neurology,Cancer,11,285387.70
3659,P07933,44.0,Female,Oncology,Fracture,12,278888.31
1679,P03835,30.0,Female,Neurology,Hypertension,10,273491.74
1587,P01350,43.0,Male,Pediatrics,Hypertension,11,273458.79
4683,P01358,55.0,Male,Orthopedics,Infection,10,273007.12
4735,P08810,61.0,Male,Pediatrics,Diabetes,11,271716.86
924,P07801,32.0,Male,Neurology,Heart Disease,10,269594.52

In [43]:
highest_cost_department = (
    df.groupby("Department")["Treatment_Cost"]
    .mean()
    .idxmax()
)

highest_average_cost = (
    df.groupby("Department")["Treatment_Cost"]
    .mean()
    .max()
)

print(f"Department: {highest_cost_department}")
print(f"Average Treatment Cost: {highest_average_cost:,.2f}")

Department: Cardiology
Average Treatment Cost: 102,040.80

In [44]:
df["Readmission"].value_counts()

Readmission
No     8146
Yes    1854
Name: count, dtype: int64

In [45]:
readmission_rate = (
    df["Readmission"].eq("Yes").mean() * 100
)

print(f"Readmission Rate: {readmission_rate:.2f}%")

Readmission Rate: 18.54%

In [46]:
readmission_by_department = (
    df.groupby("Department")["Readmission"]
    .apply(lambda x: x.eq("Yes").mean() * 100)
    .sort_values(ascending=False)
)

readmission_by_department

Department
Neurology           20.560748
Cardiology          19.875071
Pediatrics          18.525403
Orthopedics         18.369830
General Medicine    17.797138
Oncology            15.944645
Name: Readmission, dtype: float64

In [47]:
plt.figure(figsize=(10, 5))

readmission_by_department.plot(kind="bar")

plt.title("Readmission Rate by Department")
plt.xlabel("Department")
plt.ylabel("Readmission Rate (%)")
plt.xticks(rotation=45)
plt.tight_layout()
plt.savefig("../output/readmission_rate_by_department.png", dpi=150)
plt.show()

C:\Users\upadh\AppData\Local\Temp\ipykernel_9488\4099338044.py:11: UserWarning: FigureCanvasAgg is non-interactive, and thus cannot be shown
  plt.show()

In [48]:
plt.figure(figsize=(10, 5))

readmission_by_department.plot(kind="bar")

plt.title("Readmission Rate by Department")
plt.xlabel("Department")
plt.ylabel("Readmission Rate (%)")
plt.xticks(rotation=45)
plt.tight_layout()

plt.show()

C:\Users\upadh\AppData\Local\Temp\ipykernel_9488\2985696417.py:11: UserWarning: FigureCanvasAgg is non-interactive, and thus cannot be shown
  plt.show()

In [49]:
diagnosis_health = (
    df.groupby("Diagnosis")[
        ["Cholesterol", "Glucose"]
    ]
    .mean()
    .sort_values("Glucose", ascending=False)
)

diagnosis_health

               Cholesterol     Glucose
Diagnosis
Heart Disease   196.663333  107.385833
Diabetes        195.018039  107.374902
Hypertension    194.117694  107.273819
Migraine        195.653258  106.185036
Asthma          197.087127  105.994505
Infection       193.593553  105.386792
Fracture        194.125828  105.047185
Cancer          195.383112  104.727131

In [50]:
diagnosis_health = (
    df.groupby("Diagnosis")[
        ["Cholesterol", "Glucose"]
    ]
    .mean()
    .sort_values("Glucose", ascending=False)
)

diagnosis_health

               Cholesterol     Glucose
Diagnosis
Heart Disease   196.663333  107.385833
Diabetes        195.018039  107.374902
Hypertension    194.117694  107.273819
Migraine        195.653258  106.185036
Asthma          197.087127  105.994505
Infection       193.593553  105.386792
Fracture        194.125828  105.047185
Cancer          195.383112  104.727131

In [51]:
high_glucose = df[
    df["Glucose"] > 140
]

high_glucose[
    [
        "Patient_ID",
        "Age",
        "Department",
        "Diagnosis",
        "Glucose"
    ]
].sort_values(
    "Glucose",
    ascending=False
)

     Patient_ID   Age        Department      Diagnosis  Glucose
3175     P07825  65.0        Cardiology         Cancer    209.0
9555     P04001  32.0  General Medicine   Hypertension    209.0
6699     P08781  34.0  General Medicine       Fracture    208.0
3427     P08771  41.0        Cardiology       Diabetes    207.0
6131     P03955  47.0          Oncology  Heart Disease    203.0
...         ...   ...               ...            ...      ...
3531     P02707  50.0        Cardiology      Infection    141.0
3313     P00487  36.0  General Medicine       Migraine    141.0
9834     P07995  35.0       Orthopedics      Infection    141.0
5672     P05461  47.0        Cardiology   Hypertension    141.0
9858     P06669  54.0         Neurology       Fracture    141.0

[1192 rows x 5 columns]

In [52]:
print(f"Patients with high glucose: {len(high_glucose)}")

Patients with high glucose: 1192

In [53]:
high_cholesterol = df[
    df["Cholesterol"] > 240
]

high_cholesterol[
    [
        "Patient_ID",
        "Age",
        "Department",
        "Diagnosis",
        "Cholesterol"
    ]
].sort_values(
    "Cholesterol",
    ascending=False
)

     Patient_ID   Age        Department      Diagnosis  Cholesterol
2866     P09654  47.0         Neurology  Heart Disease        326.0
4462     P07037  19.0          Oncology         Cancer        314.0
604      P01255  70.0        Cardiology       Fracture        313.0
408      P00440  47.0        Cardiology       Fracture        308.0
853      P03799  30.0  General Medicine       Migraine        306.0
...         ...   ...               ...            ...          ...
5452     P02619  56.0        Cardiology       Fracture        241.0
2290     P02055  23.0         Neurology       Migraine        241.0
3214     P02577  74.0         Neurology      Infection        241.0
9280     P04301  40.0         Neurology      Infection        241.0
421      P07663  35.0        Cardiology      Infection        241.0

[936 rows x 5 columns]

In [54]:
print(f"Patients with high cholesterol: {len(high_cholesterol)}")

Patients with high cholesterol: 936

In [55]:
high_heart_rate = df[
    df["Heart_Rate"] > 100
]

high_heart_rate[
    [
        "Patient_ID",
        "Age",
        "Department",
        "Diagnosis",
        "Heart_Rate"
    ]
].sort_values(
    "Heart_Rate",
    ascending=False
)

     Patient_ID   Age        Department      Diagnosis  Heart_Rate
8768     P05393  49.0          Oncology   Hypertension       122.0
2711     P09661  47.0        Pediatrics      Infection       121.0
6486     P05843  21.0  General Medicine      Infection       118.0
9362     P07410  69.0        Cardiology       Fracture       118.0
2111     P02488  47.0         Neurology         Cancer       117.0
...         ...   ...               ...            ...         ...
653      P04519  54.0       Orthopedics      Infection       101.0
658      P02418  54.0  General Medicine       Migraine       101.0
9298     P05116  57.0       Orthopedics       Fracture       101.0
9903     P00392  56.0          Oncology       Fracture       101.0
9841     P08902  51.0          Oncology  Heart Disease       101.0

[295 rows x 5 columns]

In [56]:
print(f"Patients with high heart rate: {len(high_heart_rate)}")

Patients with high heart rate: 295

# Final Data Set check

In [57]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 19 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Patient_ID      10000 non-null  str
 1   Age             10000 non-null  float64
 2   Gender          10000 non-null  str
 3   Department      10000 non-null  str
 4   Blood_Pressure  10000 non-null  str
 5   Heart_Rate      10000 non-null  float64
 6   Temperature     10000 non-null  float64
 7   Cholesterol     10000 non-null  float64
 8   Glucose         10000 non-null  float64
 9   Diagnosis       10000 non-null  str
 10  Admission_Type  10000 non-null  str
 11  Length_of_Stay  10000 non-null  int64
 12  Treatment_Cost  10000 non-null  float64
 13  Readmission     10000 non-null  str
 14  Age_Group       10000 non-null  category
 15  Systolic        10000 non-null  int64
 16  Diastolic       10000 non-null  int64
 17  High_Risk       10000 non-null  bool
 18  Cost_Per_Day    10000 non-null  float64
dtypes: bool(1), category(1), float64(7), int64(3), str(7)
memory usage: 1.3 MB

In [58]:
df.isnull().sum()

Patient_ID        0
Age               0
Gender            0
Department        0
Blood_Pressure    0
Heart_Rate        0
Temperature       0
Cholesterol       0
Glucose           0
Diagnosis         0
Admission_Type    0
Length_of_Stay    0
Treatment_Cost    0
Readmission       0
Age_Group         0
Systolic          0
Diastolic         0
High_Risk         0
Cost_Per_Day      0
dtype: int64

In [59]:
df.head()

,Patient_ID,Age,Gender,Department,Blood_Pressure,Heart_Rate,Temperature,Cholesterol,Glucose,Diagnosis,Admission_Type,Length_of_Stay,Treatment_Cost,Readmission,Age_Group,Systolic,Diastolic,High_Risk,Cost_Per_Day
0,P07402,58.0,Female,Orthopedics,119/73,64.0,100.0,197.0,60.0,Heart Disease,Referral,5,91183.33,No,Middle Age,119,73,False,18236.666000
1,P05835,47.0,Female,General Medicine,107/91,62.0,98.8,215.0,92.0,Migraine,Referral,5,71104.32,No,Middle Age,107,91,True,14220.864000
2,P02123,47.0,Male,Orthopedics,148/98,83.0,96.0,196.0,133.0,Fracture,Routine,7,135197.73,No,Middle Age,148,98,True,19313.961429
3,P08789,47.0,Male,Oncology,115/84,89.0,100.1,224.0,119.0,Hypertension,Referral,6,146462.06,No,Middle Age,115,84,False,24410.343333
4,P00305,47.0,Female,Orthopedics,128/62,77.0,100.3,184.0,113.0,Hypertension,Emergency,6,57510.66,No,Middle Age,128,62,False,9585.110000

In [60]:
df.to_csv(
    "../output/patient_clinical_data_cleaned.csv",
    index=False
)

print("Cleaned dataset saved successfully.")

Cleaned dataset saved successfully.